version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: topuniversityindia_app
    restart: always
    ports:
      - "8000:8000"
    depends_on:
      mongo:
        condition: service_healthy
    env_file:
      - .env
      - ./server/.env
      - ./client/.env
    volumes:
      - ./server:/app/server
      - ./client:/app/client
      - /app/server/node_modules
      - /app/client/node_modules
    environment:
      NODE_ENV: production
